export const SUB_ROUTES = Object.freeze({
  PRODUCT: '/product',
  BIKE: '/bike',
  BIKES: '/bikes',
  BLOG: '/blog',
  BIKE_ACCESSORIES: '/bike-accessories',
  ADMIN: '/admin'
})

export const ROUTES = Object.freeze({
  BASE_URL: '/',
  PRODUCT_DETAIL: `${SUB_ROUTES.PRODUCT}/:productCategory/:productItem/:productId`,
  PRODUCT_CATALOG: '/product-catalog',
  PRODUCT_CATALOG_WITH_CATEGORY: '/product-catalog/:productCategory',
  BIKES: `/:bikeType${SUB_ROUTES.BIKES}`,
  BIKES_WITH_BRAND: `/:bikeType${SUB_ROUTES.BIKES}/:bikeBrand`,
  BIKE_DETAIL: `${SUB_ROUTES.BIKE_ACCESSORIES}/:bikeType${SUB_ROUTES.BIKE}/:bikeBrand/:bikeModel/:bikeId`,
  BIKE_DETAIL_WITH_CATEGORY: `${SUB_ROUTES.BIKE_ACCESSORIES}/:bikeType${SUB_ROUTES.BIKE}/:bikeBrand/:bikeModel/:bikeId/:productCategory`,
  BLOGS: '/blogs',
  BLOG_DETAIL: `${SUB_ROUTES.BLOG}/:id`,
  OUR_STORIES: '/our-stories',
  CART: '/cart',
  SEARCH: '/search',
  CONTACT_US:'/contact-us',
  CHECKOUT:'/checkout',
  PAGE_NOT_FOUND: '/page-not-found',
  ORDER_LIST: '/my-orders',
  ORDER_DETAILS:  `/my-orders/:id`,
  PROFILE: '/profile',
  WISHLIST: '/wishlist',
  TERMSANDCONDITIONS:'/terms-and-conditions',
  DISCLAIMER: '/disclaimer',
  PRIVACYPOLICY: '/privacy-policy',
  RETURN_EXCHANGE: '/return-and-exchange',
  ORDER_SUCCESSFUL: '/success/thank-you',
  ADMIN: SUB_ROUTES.ADMIN,
  ADMIN_LOGIN: `${SUB_ROUTES.ADMIN}/login`,
  ADMIN_DASHBOARD: `${SUB_ROUTES.ADMIN}/dashboard`,
  ADMIN_PRODUCTS: `${SUB_ROUTES.ADMIN}/products`,
  ADMIN_ACTIVE_CARTS: `${SUB_ROUTES.ADMIN}/active-carts`,
  ADMIN_ORDER_LIST: `${SUB_ROUTES.ADMIN}/orders`,
  ANY: '*'
})
